// English dictionary. Same shape as content/tr.ts (type-checked: a missing key fails the build,
// so a half-translated page cannot ship). Links point to English routes. Circulars stay
// Turkish-only by decision; English insights and guides are written for English readers.
// [BİLGİ GİRİLECEK] TASLAK ÇEVİRİ: yayın öncesi profesyonel çevirmen ve sorumlu YMM onayı gerekir.
// Terminology: see content/en/services.ts header.
import type { Dictionary } from './tr';
import { legalName } from '@/lib/site';

const whatsappEn =
  'https://wa.me/905350297913?text=Hello%2C%20I%20would%20like%20to%20learn%20more%20about%20MarkaDenetim.';

export const en: Dictionary = {
  locale: 'en',
  meta: {
    title: 'MarkaDenetim | Sworn-in CPA and Independent Audit in Türkiye',
    description:
      'Sworn-in CPA (YMM) services, full certification, independent audit, tax and financial advisory in Istanbul and Mardin, Türkiye.',
    ogDescription: 'Sworn-in CPA (YMM) services, independent audit, tax and financial advisory. Istanbul and Mardin.',
  },
  print: { source: 'Source' },
  a11y: {
    skip: 'Skip to content',
    breadcrumbHome: 'Home',
    language: 'Language',
    home: 'MarkaDenetim, top of page',
    mainNav: 'Main navigation',
    mobileNav: 'Mobile navigation',
    menu: 'Menu',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    pauseVideo: 'Pause background video',
    playVideo: 'Play background video',
  },
  nav: [
    { href: '/en/about', label: 'About' },
    { href: '/en/services', label: 'Services' },
    { href: '/en/sectors', label: 'Sectors', footer: false },
    { href: '/en#team', label: 'Our team', footer: false },
    { href: '/en/insights', label: 'Insights' },
    { href: '/en/contact', label: 'Contact' },
  ],
  navMenu: {
    insights: [
      { href: '/en/insights', label: 'Insights', meta: 'Tax, audit and finance' },
      { href: '/en/guides', label: 'Guides', meta: 'Practical answers for investors' },
      { href: '/en/tax-calendar', label: 'Tax calendar', meta: 'This month’s deadlines' },
    ],
    allServices: 'All services',
    allTeam: 'Meet the team',
    allSectors: 'All sectors',
    about: [
      { href: '/en/about', label: 'About us', meta: 'Firm, authorisations and principles' },
      { href: '/en/about/chairmans-message', label: 'Chairman’s message', meta: 'Fatih Olgun, YMM' },
      { href: '/en/quality-and-independence', label: 'Quality and independence', meta: 'Ethics, transparency, authorisation' },
    ],
    submenu: 'submenu',
  },
  cta: { label: 'Get in touch', href: '/en/contact' },
  mobileBar: {
    label: 'Quick contact',
    whatsapp: { label: 'WhatsApp', href: whatsappEn },
    form: { label: 'Request a quote', href: '/en/contact#contact-form' },
    call: { label: 'Call', href: 'tel:+905350297913' },
  },
  quoteTab: {
    label: 'Request a quote',
    kicker: 'Quote and meeting',
    title: 'Send us your request',
    lead: 'Briefly describe your matter and the responsible partner will get in touch. Your information is protected under our confidentiality principles.',
    close: 'Close panel',
  },
  contact: {
    phoneLabel: 'Phone',
    phone: '+90 535 029 79 13',
    emailLabel: 'Email',
    email: 'info@markadenetim.tr',
  },
  hero: {
    lines: ['We examine.', 'We verify.', 'We sign.'],
    lead: 'We examine every declared figure against its evidence, verify it, and take responsibility for it with our signature.',
    cta: { label: 'Request a meeting', href: '/en#contact' },
    tag: 'Sworn-in CPA and Audit',
    scenes: ['City', 'Energy', 'Harvest'],
    hud: { scene: 'Scene', pause: 'Pause', play: 'Play' },
  },
  about: {
    metaTitle: 'About Us: Sworn-in CPA and Audit Firm',
    metaDescription:
      'MarkaDenetim is a professional firm providing sworn-in CPA (YMM) services, full certification, VAT refund certification and independent audit under Law No. 3568.',
    hero: {
      kicker: 'About us',
      lines: ['We stand', 'behind our', 'signature.'],
      lead: 'MarkaDenetim is a sworn-in CPA and independent audit firm subject to Law No. 3568. We carry responsibility for every document we certify.',
      facts: [
        { label: 'Profession', value: 'Sworn-in CPA (YMM)' },
        { label: 'Legal basis', value: 'Law No. 3568' },
        { label: 'Audit authorisation', value: 'KGK-licensed independent audit' },
        { label: 'Offices', value: 'Istanbul · Mardin' },
      ],
      sealCaption: 'Signature · Seal · Certification',
    },
    lexicon: {
      label: 'The title',
      title: 'Our professional title is the definition of our work.',
      // The Turkish title is kept: each word is explained for an international reader
      words: [
        {
          word: 'Yeminli',
          kind: 'adj.',
          kindTitle: 'adjective',
          text: 'Sworn. The profession begins with an oath and is practised under duties of integrity, impartiality and confidentiality.',
        },
        {
          word: 'Mali',
          kind: 'adj.',
          kindTitle: 'adjective',
          text: 'Financial. Its subject is the books, returns and financial statements of a business; every amount is assessed against evidence.',
        },
        {
          word: 'Müşavir',
          kind: 'n.',
          kindTitle: 'noun',
          text: 'Advisor. Gives an opinion to management and shares findings in writing, with their basis and in plain language.',
        },
      ],
    },
    ledger: {
      label: 'Certification and audit',
      title: 'Documents that carry our signature.',
      intro: 'Every certification and audit engagement starts with a written scope and ends with a documented report.',
      columns: { subject: 'Subject', scope: 'Scope', basis: 'Basis', output: 'Output' },
      rows: [
        {
          subject: 'Full certification',
          scope: 'Consistency of the corporate tax return with statutory books and records',
          basis: 'Law No. 3568 and the certification regulation',
          output: 'Full certification report',
        },
        {
          subject: 'VAT refund certification',
          scope: 'Refund claims arising from exports, reduced rates and withholding',
          basis: 'VAT Law No. 3065 and the implementation communiqué',
          output: 'VAT refund certification report',
        },
        {
          subject: 'Incentive certificate closing',
          scope: 'Investment expenditure and records under an incentive certificate',
          basis: 'Legislation on state aid for investments',
          output: 'Determination report',
        },
        {
          subject: 'Special-purpose certification',
          scope: 'Other transactions where legislation requires sworn-in CPA certification',
          basis: 'Relevant specific legislation',
          output: 'Special-purpose report',
        },
        {
          subject: 'Independent audit',
          scope: 'Audit of financial statements under independent auditing standards',
          basis: 'Turkish Commercial Code No. 6102 and KGK regulations',
          output: 'Independent auditor’s report',
        },
      ],
      cta: 'Explore our services',
    },
    responsibility: {
      label: 'Responsibility',
      statement: 'A certification is a written promise that the figures are true.',
      lawMark: 'Law No. 3568, Art. 12',
      law: 'A sworn-in CPA is responsible for the accuracy of the documents they certify. In the event of a certification contrary to the facts, they are held jointly and severally liable with the taxpayer for the tax loss and penalties.',
      note: 'This is why every certification we issue rests on a verified, traceable working file.',
      principlesLabel: 'Our working principles',
      principles: [
        { title: 'Expertise', text: 'Every engagement is undertaken and signed by an authorised professional.' },
        { title: 'Trust', text: 'Every piece of information we obtain is protected by professional secrecy.' },
        { title: 'Discipline', text: 'Every engagement follows the same steps; every step is recorded.' },
        { title: 'Transparency', text: 'We share our findings openly with management before reporting.' },
      ],
    },
    partners: {
      label: 'Responsible partners',
      title: 'There is a name under every report.',
      intro: 'Every engagement is carried out under the supervision of a sworn-in CPA or responsible auditor who takes responsibility for it.',
      profile: 'View profile',
      all: 'Meet the whole team',
    },
    authority: {
      label: 'Authorisation and registration',
      title: 'A registered, auditable firm.',
      scopeLabel: 'Independent audit authorisations',
      // [BİLGİ GİRİLECEK] Yayın öncesi yetki belgeleriyle doğrulanmalı
      bodies: [
        { abbr: 'KGK', name: 'Public Oversight, Accounting and Auditing Standards Authority' },
        { abbr: 'SPK', name: 'Capital Markets Board' },
        { abbr: 'BDDK', name: 'Banking Regulation and Supervision Agency' },
        { abbr: 'EPDK', name: 'Energy Market Regulatory Authority' },
        { abbr: 'Insurance', name: 'Insurance sector' },
      ],
      registryLabel: 'Registration details',
    },
    closing: {
      title: 'Let us read the structure behind the figures together.',
      lead: 'Let us clarify your certification, audit or tax needs in a short meeting.',
      cta: 'Request a meeting',
      secondary: 'Our services',
    },
  },
  services: {
    kicker: 'Areas of expertise',
    title: 'Four areas, one discipline.',
    intro:
      'We define the scope of every engagement in writing from the outset and carry it out under the supervision of a responsible professional.',
    cta: 'All services',
    page: {
      metaTitle: 'Services: Certification, Audit, Tax and Advisory',
      metaDescription:
        'Sworn-in CPA services and certification, independent audit, tax advisory, VAT refunds, information systems audit and KVKK compliance in Türkiye.',
      kicker: 'Services',
      lines: ['Our areas', 'of expertise.'],
      lead: 'From certification to independent audit, from tax to information systems: every engagement is supervised by a professional who takes responsibility for it.',
      groups: { temel: 'Core areas', uzman: 'Specialised services' },
      closing: { title: 'Not sure which area your matter falls under?', cta: 'Let us find out together' },
    },
    detail: {
      back: 'All services',
      kicker: 'Area of expertise',
      onThisPage: 'On this page',
      scope: 'Scope',
      process: 'Approach',
      processTitle: 'Every engagement follows the same four-step discipline.',
      deliverables: 'Deliverables',
      deliverablesTitle: 'Every engagement ends with a written deliverable.',
      basis: 'Authorisation and legal basis',
      cta: 'Request a meeting',
      others: 'Other areas of expertise',
      disclaimer: 'The information on this page is general in nature and does not replace an assessment of your specific situation.',
    },
  },
  team: {
    title: 'Our Team',
    intro: 'Every engagement is carried out under the supervision of a sworn-in CPA or responsible auditor who takes responsibility for it.',
    profile: 'View profile',
    back: 'Our team',
    about: 'About',
    focus: 'Areas of expertise',
    contact: 'Contact',
    email: 'Email',
    next: 'Next team member',
    cta: 'Request a meeting',
    emailCta: 'Send an email',
    portraitAlt: 'Portrait of {name}',
    focusMeta: 'Areas of expertise',
  },
  approach: {
    title: 'Our approach',
    intro: 'We follow the same four-stage discipline in every engagement: first we understand the structure, then we clarify the points to be decided together.',
    scopeLabel: 'At this stage',
    outputLabel: 'Output',
    riskLevels: ['HIGH', 'MEDIUM', 'LOW'],
    steps: [
      {
        title: 'Analysis',
        text: 'We review the financial statements, bookkeeping and regulatory obligations together. These initial findings define the scope of the work.',
        scope: ['Financial statements and chart of accounts', 'Bookkeeping and internal control', 'Legal and filing obligations'],
        output: 'Scope and initial findings memo',
        figure: 'Scattered data is brought into a single view',
      },
      {
        title: 'Assessment',
        text: 'We classify findings by significance and risk. Every finding is recorded together with its supporting document.',
        scope: ['Classification by significance and risk', 'Matching findings to supporting evidence', 'Discussion of findings with management'],
        output: 'Documented findings file',
        figure: 'Findings are separated by risk level',
      },
      {
        title: 'Strategy',
        text: 'Together with management we set priorities and practical steps. Recommendations are shaped by the structure and timeline of the business.',
        scope: ['Setting priorities with management', 'Practical steps and responsibilities', 'A roadmap suited to the business calendar'],
        output: 'Prioritised action plan',
        figure: 'Steps fall into order of priority',
      },
      {
        title: 'Outcome',
        text: 'The report, certification or opinion is delivered in plain language. We follow up on implementation together.',
        scope: ['Reading the report together with management', 'Setting the implementation timeline', 'Periodic follow-up meetings'],
        output: 'Report, certification or professional opinion',
        figure: 'The structure becomes clear, the decision is recorded',
      },
    ],
  },
  trust: {
    label: 'Our working principles',
    quote: {
      lead: 'Trust is built on ',
      emphasis: 'documented, verified and timely',
      tail: ' information.',
    },
    commitments: [
      {
        mark: 'Principle I',
        title: 'Independence',
        text: 'Before every audit and certification engagement, we assess any relationship that could affect our independence.',
      },
      {
        mark: 'Principle II',
        title: 'Confidentiality',
        text: 'Every piece of information obtained during our work is protected by professional secrecy and under KVKK.',
      },
      {
        mark: 'Principle III',
        title: 'Professional standards',
        text: 'We carry out our work in line with applicable legislation, professional principles and the relevant auditing standards.',
      },
    ],
    credentialsLabel: 'Authorisation and registration details',
    // [BİLGİ GİRİLECEK] Değerler Türkçe sürümle aynı kaynaktan doğrulanmalı
    credentials: [
      { label: 'YMM Chamber / TÜRMOB registration number', value: 'Istanbul YMM Chamber — Reg. No: 34/19284' },
      { label: 'KGK independent audit authorisation', value: 'BDK / 2019 / 0482' },
      { label: 'Trade registry and MERSİS number', value: 'ITO: 842195-5 · MERSİS: 0612048192300001' },
      { label: 'Responsible sworn-in CPA', value: 'Fatih Olgun (YMM, Responsible Auditor)' },
    ],
  },
  insights: {
    title: 'Insights',
    sample: '',
    all: { label: 'All insights', href: '/en/insights' },
    minutes: 'min read',
    page: {
      title: 'Insights',
      metaTitle: 'Insights: Tax, Audit and Finance',
      intro: 'Short, practical notes on developments in tax, audit and finance.',
      featured: 'Featured',
      index: 'All insights',
    },
    article: {
      back: 'All insights',
      contents: 'In this article',
      more: 'More insights',
      dateLabel: 'Date',
      readingLabel: 'Reading time',
      statusLabel: 'Status',
      disclaimer:
        'This article is for general information and does not constitute professional advice. Please contact us for an assessment of your own situation.',
      cta: { label: 'Request a meeting', href: '/en/contact' },
    },
  },
  contactSection: {
    kicker: 'Contact',
    title: 'Let us review your financial structure more clearly.',
    lead: 'You can send your meeting request through the form or contact us directly. Every enquiry is handled under our confidentiality principles.',
    channelsLabel: 'Contact us directly',
    channels: [
      { label: 'Phone · Istanbul', value: '+90 535 029 79 13', href: 'tel:+905350297913' },
      { label: 'Phone · Mardin', value: '+90 541 811 80 86', href: 'tel:+905418118086' },
      { label: 'Email', value: 'info@markadenetim.tr', href: 'mailto:info@markadenetim.tr' },
      { label: 'WhatsApp', value: 'Send a message', href: whatsappEn, external: true },
    ],
    hours: { label: 'Office hours', value: 'Monday – Friday · 08:30 – 18:00 (GMT+3)' },
    newTab: '(opens in a new tab)',
    form: {
      title: 'Write to us',
      note: 'All fields are required unless stated otherwise.',
      topics: ['Sworn-in CPA services', 'Independent audit', 'Tax advisory', 'Financial advisory', 'Other'],
      fields: {
        name: 'Full name',
        company: 'Company',
        email: 'Email',
        subject: 'Subject',
        message: 'Your message',
      },
      optional: '(optional)',
      consentBefore: 'I have read the ',
      consentLink: 'KVKK Privacy Notice',
      consentAfter: ' and consent to the processing of my personal data in order to respond to my enquiry.',
      honeypot: 'Leave this field empty',
      submit: 'Send message',
      sending: 'Sending',
      success: 'Your message has been received. We will get back to you shortly.',
      successTitle: 'Thank you.',
      again: 'Write a new message',
      counter: 'characters',
      errors: {
        name: 'Please enter your full name.',
        email: 'Please enter a valid email address.',
        subject: 'Please select a subject.',
        message: 'Please enter your message (at least 10 characters).',
        consent: 'Please tick the KVKK consent box to continue.',
        summary: 'Some fields in the form need attention.',
        server: 'Your message could not be sent. Please try again in a few minutes or write to us by email.',
      },
    },
  },
  contactPage: {
    metaTitle: 'Contact: Istanbul and Mardin Offices',
    metaDescription:
      'Send your meeting request to MarkaDenetim. Reach our Istanbul and Mardin offices by phone, email, WhatsApp or the contact form.',
    kicker: 'Contact',
    lines: ['Let us', 'clarify your', 'questions together.'],
    lead: 'You can reach us by phone, email or the form. Your enquiry is passed to the responsible partner according to its subject.',
    offices: 'Office addresses and maps',
    plate: {
      points: [
        { city: 'ISTANBUL', coords: '41°00′ N · 28°39′ E' },
        { city: 'MARDIN', coords: '37°18′ N · 40°44′ E' },
      ],
      caption: 'Two offices · One discipline',
    },
    process: {
      label: 'How it works',
      title: 'Every enquiry reaches a person.',
      steps: [
        { title: 'We receive your enquiry', text: 'The matter you send by form, email or phone is recorded.' },
        { title: 'It goes to the right partner', text: 'Your enquiry is directed according to its subject: certification, audit, tax or financial advisory.' },
        { title: 'An initial meeting', text: 'We clarify your needs and the scope together. The initial meeting creates no commitment.' },
      ],
      privacy: 'Information you share is protected by professional secrecy and our confidentiality principles.',
    },
  },
  finder: {
    label: 'Search',
    placeholder: 'Search titles and content',
    topics: 'Topic',
    all: 'All',
    results: 'results',
    none: 'No content matches your search.',
    clear: 'Clear filters',
  },
  pagination: {
    label: 'Pagination',
    prev: 'Previous',
    next: 'Next',
    page: 'Page',
    titleSuffix: 'Page',
  },
  taxCalendar: {
    kicker: 'Filing and payment deadlines',
    title: 'Tax calendar',
    metaTitle: 'Turkish Tax Calendar: Monthly Filing and Payment Deadlines',
    intro: 'This month’s Turkish tax filing and payment deadlines in one list. Deadlines falling on weekends or public holidays are moved to the next business day.',
    next: 'Next deadline',
    today: 'Today',
    daysLeft: 'days left',
    passed: 'Passed',
    shifted: 'Moved due to a holiday',
    period: 'Period',
    prev: 'Previous month',
    nextMonth: 'Next month',
    current: 'This month',
    empty: 'No deadlines listed for this month.',
    noteTitle: 'Important note',
    note: 'This calendar is for general information. Dates may change due to religious holidays, administrative leave and legislative changes; the Revenue Administration’s tax calendar is authoritative.',
    gib: { label: 'Revenue Administration (GİB)', href: 'https://www.gib.gov.tr/' },
    cta: 'Discuss your filing obligations',
  },
  sectorsPage: {
    kicker: 'Sector-specific obligations',
    title: 'Sectors',
    metaTitle: 'Sectors: Export, Construction, Energy, Finance, Industry and Technology',
    intro: 'Every sector has its own tax, certification and reporting obligations. We bring our services together around them.',
    read: 'Explore sector',
    num: 'Sector',
    servicesCount: 'related services',
    matrix: {
      label: 'At a glance',
      title: 'Sectors and services',
      text: 'See which services are most relevant to each sector in a single table. Each mark links to the related service.',
      sector: 'Sector',
      related: 'Related',
      scrollHint: 'Scroll the table sideways',
    },
    back: 'All sectors',
    overview: 'Overview',
    topics: 'Sector-specific matters',
    support: 'How we help',
    related: 'Related services',
    others: 'Other sectors',
    disclaimer: 'The information on this page is general in nature; obligations specific to your business are assessed together in an initial meeting.',
    cta: 'Request a meeting',
  },
  circularsPage: {
    kicker: 'Regulatory updates',
    title: 'Circulars',
    metaTitle: 'Circulars: Tax and Regulatory Updates',
    intro: 'Numbered updates on developments in tax and professional legislation, each published under the signature of the responsible professional.',
    sample: 'Sample circular — to be replaced with real circulars before publication',
    back: 'All circulars',
    contents: 'In this circular',
    read: 'Read circular',
    date: 'Date',
    topic: 'Topic',
    signature: 'Signature',
    publisher: 'Published by',
    profile: 'View profile',
    disclaimer: 'This circular is for general information and does not constitute professional advice.',
    cta: 'Request a meeting',
  },
  guidesPage: {
    kicker: 'Knowledge centre',
    title: 'Guides',
    metaTitle: 'Guides: Certification, Audit, Tax and Compliance in Türkiye',
    intro: 'Plain answers to the questions our clients ask most often, step by step.',
    back: 'All guides',
    contents: 'In this guide',
    read: 'Read guide',
    num: 'Guide',
    service: 'Related service',
    disclaimer:
      'This guide is for general information; amounts, rates and deadlines may change over time. Please contact us for an assessment of your own situation.',
    cta: 'Request a meeting',
  },
  chairman: {
    metaTitle: 'Chairman’s Message',
    metaDescription: 'Message from Fatih Olgun, Sworn-in CPA and Chairman of the Board of MarkaDenetim, and his professional path.',
    kicker: 'Chairman’s message',
    quote: 'A signature is worth as much as the responsibility it carries.',
    draft: 'Draft — awaiting approval',
    message: [
      'Throughout a career that took me from tax inspector to sworn-in CPA, the most important thing I have learned is this: the signature at the bottom of a document is a written promise that the document is true.',
      'We founded MarkaDenetim as a firm that understands the weight of that promise. In every report we certify and every set of financial statements we audit, we ask the same question: do we stand behind this signature?',
      'We build our relationships with clients on independence and confidentiality. Placing business decisions on a sound financial footing is only possible with accurate information and plain language.',
      'Together with our team, we will continue to carry the responsibility our profession places on us with the same care every day.',
    ],
    pathLabel: 'Professional path',
    path: [
      { title: 'Tax Inspector', text: 'Tax inspection and audit in public service.', year: '[YEAR]' },
      { title: 'Sworn-in CPA', text: 'Certification and advisory under Law No. 3568.', year: '[YEAR]' },
      { title: 'Chairman of the Board, MarkaDenetim', text: 'Leadership of the firm and responsibility for certification.', year: '[YEAR]' },
    ],
    focusLabel: 'Areas of expertise',
    profile: 'View profile',
    circulars: 'Signed circulars',
  },
  quality: {
    metaTitle: 'Quality, Independence and Transparency',
    metaDescription:
      'MarkaDenetim’s independence principles, approach to quality management, ethics rules, transparency reports and authorisations.',
    kicker: 'Quality and independence',
    title: 'Trust is not declared; it is demonstrated.',
    lead: 'Certification and independent audit are only meaningful in a firm whose independence is beyond doubt. Here you can find our working principles, our approach to quality and our authorisations.',
    contents: 'On this page',
    sections: [
      {
        id: 'independence',
        title: 'Independence',
        text: 'Independence is the first condition of the value of our opinion. We work as required by the independent auditing standards and the Code of Ethics:',
        items: [
          'An independence and conflict-of-interest assessment is carried out before every engagement.',
          'No service that would impair independence is provided to an audited entity.',
          'The engagement team declares that it has no financial interest in the audited entity.',
        ],
      },
      {
        id: 'quality',
        title: 'Quality management',
        text: 'Quality begins when an engagement is accepted, not on the last page of the report. Our approach rests on the following elements:',
        items: [
          'Acceptance and continuance: every engagement is assessed for competence and independence before acceptance.',
          'Team competence: engagements are carried out under the supervision of experienced professionals.',
          'Review: reports are reviewed before signature; where the standards require, this review is performed by a professional outside the engagement team.',
          'Monitoring: the quality management system is monitored and improved regularly.',
        ],
        note: '[TO BE COMPLETED] Firm-specific description of the quality management system.',
      },
      {
        id: 'confidentiality',
        title: 'Confidentiality and professional secrecy',
        text: 'Information obtained during our engagements is a professional secret. It is not shared with third parties except where required by law, and personal data is protected under Law No. 6698.',
      },
      {
        id: 'ethics',
        title: 'Ethics',
        text: 'Our work is based on TÜRMOB’s professional ethics rules and the Code of Ethics published by KGK: integrity, objectivity, professional competence and due care, confidentiality and professional behaviour.',
      },
    ],
    reports: {
      id: 'transparency',
      title: 'Transparency reports',
      text: 'Our transparency reports, published where required by legislation, are listed below.',
      items: [
        { year: '[YEAR]', label: 'Transparency report', status: '[PDF TO BE UPLOADED]' },
        { year: '[YEAR]', label: 'Transparency report', status: '[PDF TO BE UPLOADED]' },
      ],
    },
    credentials: { id: 'authorisation', title: 'Authorisation and registration details' },
    cta: 'Request a meeting',
  },
  footer: {
    // Tüzel kişilik türü (A.Ş.) çevrilmez; resmi unvan footer'da legalName ile Türkçe kalır
    descriptor: 'Sworn-in CPA and Audit',
    signature: 'Every certification is a responsibility. We sign with independence, confidentiality and professional care.',
    socialLabel: 'Follow us',
    social: [
      { name: 'LinkedIn', href: 'https://www.linkedin.com/' },
      { name: 'Instagram', href: 'https://www.instagram.com/' },
      { name: 'X', href: 'https://x.com/' },
    ],
    copyright: legalName,
    officesLabel: 'Our offices',
    officesTitle: 'In Istanbul and Mardin, with the same discipline.',
    directionsLabel: 'Get directions',
    mapTitle: 'location map',
    // Addresses are kept in Turkish: they are postal addresses
    offices: [
      {
        city: 'Istanbul Head Office',
        address: 'Barış Mah. Necip Fazıl Kısakürek Sokak No:1 Lotus İş Merkezi C Blok Kat:5 Ofis No:15, Beylikdüzü / İstanbul',
        phone: '+90 535 029 79 13',
        phoneHref: 'tel:+905350297913',
        email: 'info@markadenetim.tr',
        mapUrl: 'https://maps.google.com/maps?q=41.0094323,28.6538803+(Marka%20Denetim%20%C4%B0stanbul%20Merkez%20Ofis)&t=&z=16&ie=UTF8&iwloc=&output=embed',
        directionsUrl: 'https://maps.google.com/?q=41.0094323,28.6538803',
      },
      {
        city: 'Mardin Office',
        address: 'Sanayi Mah. 705 Sokak Biriz Yapı İş Merkezi No:2 Ofis No:28 Merkez / Mardin',
        phone: '+90 541 811 80 86',
        phoneHref: 'tel:+905418118086',
        email: 'info@markadenetim.tr',
        mapUrl: 'https://maps.google.com/maps?q=Sanayi+Mah.+705+Sokak+Biriz+Yap%C4%B1+%C4%B0%C5%9F+Merkezi+No:2+Merkez+Mardin&t=&z=15&ie=UTF8&iwloc=&output=embed',
        directionsUrl: 'https://maps.google.com/?q=Sanayi+Mah.+705+Sokak+Biriz+Yap%C4%B1+%C4%B0%C5%9F+Merkezi+No:2+Merkez+Mardin',
      },
    ],
    legal: [
      { href: '/en/privacy', label: 'Privacy' },
      { href: '/en/privacy-notice', label: 'KVKK Privacy Notice' },
      { href: '/en/cookies', label: 'Cookie Policy' },
    ],
    legalNav: 'Legal information',
    footerNav: 'Footer navigation',
    sectionsLabel: 'Sections',
    contactLabel: 'Contact',
    backToTop: 'Back to top',
  },
  cookies: {
    label: 'Cookies',
    title: 'Your cookie preference',
    text: 'Our office maps are loaded from Google Maps, which may use cookies. If you do not consent, the maps will not load; all other functions of the site continue to work.',
    policy: 'Cookie Policy',
    accept: 'Accept',
    reject: 'Necessary only',
    manage: 'Cookie preferences',
    mapBlocked: 'The map was not loaded because of your cookie preference.',
    mapLoad: 'Show map',
  },
  status: {
    home: 'Back to home',
    linksLabel: 'You can continue here',
    links: [
      { href: '/en/services', label: 'Our services' },
      { href: '/en/insights', label: 'Insights' },
      { href: '/en/contact', label: 'Contact' },
    ],
    notFound: {
      code: '404',
      label: 'Page not found',
      title: 'The page you are looking for is not here.',
      text: 'The link may have changed or the page may have been removed. You can continue with the links below.',
    },
    error: {
      code: '500',
      label: 'Unexpected error',
      title: 'This page cannot be displayed right now.',
      text: 'A temporary problem occurred. You can try again or return to the home page.',
      retry: 'Try again',
      digest: 'Error code',
    },
  },
  legal: {
    back: 'Back to home',
    updated: 'Last updated',
    pages: {
      kvkk: {
        title: 'KVKK Privacy Notice',
        description: `Privacy notice of ${legalName} on the processing of personal data under Personal Data Protection Law No. 6698 (KVKK).`,
      },
      gizlilik: {
        title: 'Privacy Policy',
        description: `Privacy policy of ${legalName}: how information about website visitors is protected.`,
      },
      cerez: {
        title: 'Cookie Policy',
        description: 'Cookies used on the MarkaDenetim website, their purposes and how to manage your preferences.',
      },
    },
  },
};
